/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CardComponent: typeof import('./src/components/CardComponent.vue')['default']
    CardGrid: typeof import('./src/components/CardGrid.vue')['default']
    ConfirmationFormComponent: typeof import('./src/components/ConfirmationFormComponent.vue')['default']
    Controls: typeof import('./src/components/editor/Controls.vue')['default']
    DashboardComponent: typeof import('./src/components/DashboardComponent.vue')['default']
    DeleteFormComponent: typeof import('./src/components/DeleteFormComponent.vue')['default']
    Editor: typeof import('./src/components/editor/Editor.vue')['default']
    HeaderComponent: typeof import('./src/components/HeaderComponent.vue')['default']
    HelloFormComponent: typeof import('./src/components/HelloFormComponent.vue')['default']
    LoginComponent: typeof import('./src/components/LoginComponent.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NP: typeof import('naive-ui')['NP']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Workspace: typeof import('./src/components/editor/Workspace.vue')['default']
  }
}
